/**
 * @input  lib/slash-command/registry/handlers/*
 * @output CONVERSATION_COMMAND_ENTRIES
 * @pos    会话、消息、角色、表达式与扩展命令
 * @update 一旦我被更新，务必更新所属 README 与 PRD slash command 附录。
 */

import type { CommandEntry } from "./types";
import * as ChatHandlers from "./handlers/chat";
import * as MessageHandlers from "./handlers/messages";
import * as CharacterHandlers from "./handlers/characters";
import * as ExpressionHandlers from "./handlers/expression";
import * as ExtensionHandlers from "./handlers/extensions";
import * as QuickReplyHandlers from "./handlers/quick-reply";

export const CONVERSATION_COMMAND_ENTRIES: CommandEntry[] = [
  ["chat-manager", ChatHandlers.handleChatManager],
  ["chat-history", ChatHandlers.handleChatManager],
  ["manage-chats", ChatHandlers.handleChatManager],
  ["chat-reload", ChatHandlers.handleChatReload],
  ["newchat", ChatHandlers.handleNewChat],
  ["tempchat", ChatHandlers.handleTempChat],
  ["closechat", ChatHandlers.handleCloseChat],
  ["getchatname", ChatHandlers.handleGetChatName],
  ["renamechat", ChatHandlers.handleRenameChat],
  ["setinput", ChatHandlers.handleSetInput],
  ["input", ChatHandlers.handleSetInput],
  ["forcesave", ChatHandlers.handleForceSave],
  ["hide", ChatHandlers.handleHide],
  ["unhide", ChatHandlers.handleUnhide],
  ["member-get", ChatHandlers.handleGetMember],
  ["getmember", ChatHandlers.handleGetMember],
  ["memberget", ChatHandlers.handleGetMember],
  ["member-add", ChatHandlers.handleAddMember],
  ["addmember", ChatHandlers.handleAddMember],
  ["memberadd", ChatHandlers.handleAddMember],
  ["member-remove", ChatHandlers.handleRemoveMember],
  ["removemember", ChatHandlers.handleRemoveMember],
  ["memberremove", ChatHandlers.handleRemoveMember],
  ["member-up", ChatHandlers.handleMoveMemberUp],
  ["upmember", ChatHandlers.handleMoveMemberUp],
  ["memberup", ChatHandlers.handleMoveMemberUp],
  ["member-down", ChatHandlers.handleMoveMemberDown],
  ["downmember", ChatHandlers.handleMoveMemberDown],
  ["memberdown", ChatHandlers.handleMoveMemberDown],
  ["member-peek", ChatHandlers.handlePeekMember],
  ["peek", ChatHandlers.handlePeekMember],
  ["memberpeek", ChatHandlers.handlePeekMember],
  ["peekmember", ChatHandlers.handlePeekMember],
  ["member-count", ChatHandlers.handleCountMember],
  ["countmember", ChatHandlers.handleCountMember],
  ["membercount", ChatHandlers.handleCountMember],
  ["member-disable", ChatHandlers.handleDisableMember],
  ["disable", ChatHandlers.handleDisableMember],
  ["disablemember", ChatHandlers.handleDisableMember],
  ["memberdisable", ChatHandlers.handleDisableMember],
  ["member-enable", ChatHandlers.handleEnableMember],
  ["enable", ChatHandlers.handleEnableMember],
  ["enablemember", ChatHandlers.handleEnableMember],
  ["memberenable", ChatHandlers.handleEnableMember],
  ["addswipe", ChatHandlers.handleAddSwipe],
  ["swipeadd", ChatHandlers.handleAddSwipe],
  ["reasoning-get", ChatHandlers.handleGetReasoning],
  ["get-reasoning", ChatHandlers.handleGetReasoning],
  ["reasoning-set", ChatHandlers.handleSetReasoning],
  ["set-reasoning", ChatHandlers.handleSetReasoning],
  ["reasoning-parse", ChatHandlers.handleReasoningParse],
  ["parse-reasoning", ChatHandlers.handleReasoningParse],
  ["listinjects", ChatHandlers.handleListInjects],
  ["flushinject", ChatHandlers.handleFlushInjects],
  ["flushinjects", ChatHandlers.handleFlushInjects],
  ["chat-jump", ChatHandlers.handleChatJump],
  ["chat-scrollto", ChatHandlers.handleChatJump],
  ["floor-teleport", ChatHandlers.handleChatJump],
  ["chat-render", ChatHandlers.handleChatRender],
  ["cut", ChatHandlers.handleCut],
  ["delchat", ChatHandlers.handleDelChat],
  ["delmode", ChatHandlers.handleDelMode],
  ["delete", ChatHandlers.handleDelete],
  ["delname", ChatHandlers.handleDelName],
  ["cancel", ChatHandlers.handleDelName],
  ["delswipe", ChatHandlers.handleDelSwipe],
  ["swipedel", ChatHandlers.handleDelSwipe],
  ["expression-set", ExpressionHandlers.handleExpressionSet],
  ["sprite", ExpressionHandlers.handleExpressionSet],
  ["emote", ExpressionHandlers.handleExpressionSet],
  ["expression-folder-override", ExpressionHandlers.handleExpressionFolderOverride],
  ["spriteoverride", ExpressionHandlers.handleExpressionFolderOverride],
  ["costume", ExpressionHandlers.handleExpressionFolderOverride],
  ["expression-last", ExpressionHandlers.handleExpressionLast],
  ["lastsprite", ExpressionHandlers.handleExpressionLast],
  ["expression-list", ExpressionHandlers.handleExpressionList],
  ["expressions", ExpressionHandlers.handleExpressionList],
  ["expression-classify", ExpressionHandlers.handleExpressionClassify],
  ["classify", ExpressionHandlers.handleExpressionClassify],
  ["expression-upload", ExpressionHandlers.handleExpressionUpload],
  ["uploadsprite", ExpressionHandlers.handleExpressionUpload],
  ["extension-enable", ExtensionHandlers.handleExtensionEnable],
  ["extension-disable", ExtensionHandlers.handleExtensionDisable],
  ["extension-toggle", ExtensionHandlers.handleExtensionToggle],
  ["extension-state", ExtensionHandlers.handleExtensionState],
  ["extension-exists", ExtensionHandlers.handleExtensionExists],
  ["extension-installed", ExtensionHandlers.handleExtensionExists],
  ["translate", ExtensionHandlers.handleTranslate],
  ["yt-script", ExtensionHandlers.handleYouTubeScript],
  ["qr", QuickReplyHandlers.handleQr],
  ["qr-arg", QuickReplyHandlers.handleQrArg],
  ["qr-set", QuickReplyHandlers.handleQrSet],
  ["qrset", QuickReplyHandlers.handleQrSet],
  ["qr-set-on", QuickReplyHandlers.handleQrSetOn],
  ["qr-set-off", QuickReplyHandlers.handleQrSetOff],
  ["qr-chat-set", QuickReplyHandlers.handleQrChatSet],
  ["qr-chat-set-on", QuickReplyHandlers.handleQrChatSetOn],
  ["qr-chat-set-off", QuickReplyHandlers.handleQrChatSetOff],
  ["qr-set-list", QuickReplyHandlers.handleQrSetList],
  ["qr-list", QuickReplyHandlers.handleQrList],
  ["qr-get", QuickReplyHandlers.handleQrGet],
  ["qr-create", QuickReplyHandlers.handleQrCreate],
  ["qr-update", QuickReplyHandlers.handleQrUpdate],
  ["qr-delete", QuickReplyHandlers.handleQrDelete],
  ["qr-contextadd", QuickReplyHandlers.handleQrContextAdd],
  ["qr-contextdel", QuickReplyHandlers.handleQrContextDel],
  ["qr-contextclear", QuickReplyHandlers.handleQrContextClear],
  ["qr-set-create", QuickReplyHandlers.handleQrSetCreate],
  ["qr-presetadd", QuickReplyHandlers.handleQrSetCreate],
  ["qr-set-update", QuickReplyHandlers.handleQrSetUpdate],
  ["qr-presetupdate", QuickReplyHandlers.handleQrSetUpdate],
  ["qr-set-delete", QuickReplyHandlers.handleQrSetDelete],
  ["qr-presetdelete", QuickReplyHandlers.handleQrSetDelete],
  ["getmessage", MessageHandlers.handleGetMessage],
  ["getmes", MessageHandlers.handleGetMessage],
  ["setmessage", MessageHandlers.handleEditMessage],
  ["setmes", MessageHandlers.handleEditMessage],
  ["editmessage", MessageHandlers.handleEditMessage],
  ["editmes", MessageHandlers.handleEditMessage],
  ["edit", MessageHandlers.handleEditMessage],
  ["delmessage", MessageHandlers.handleDelMessage],
  ["delmes", MessageHandlers.handleDelMessage],
  ["del", MessageHandlers.handleDelMessage],
  ["messages", MessageHandlers.handleMessages],
  ["mes", MessageHandlers.handleMessages],
  ["message", MessageHandlers.handleMessages],
  ["message-role", MessageHandlers.handleMessageRole],
  ["message-name", MessageHandlers.handleMessageName],
  ["name", MessageHandlers.handleMessageName],
  ["messagecount", MessageHandlers.handleMessageCount],
  ["mescount", MessageHandlers.handleMessageCount],
  ["char", CharacterHandlers.handleCharacter],
  ["character", CharacterHandlers.handleCharacter],
  ["go", CharacterHandlers.handleCharacter],
  ["char-find", CharacterHandlers.handleCharacterFind],
  ["findchar", CharacterHandlers.handleCharacterFind],
  ["random", CharacterHandlers.handleRandom],
  ["rename-char", CharacterHandlers.handleRenameCharacter],
  ["dupe", CharacterHandlers.handleDupe],
  ["ask", CharacterHandlers.handleAsk],
];
