/**
 * @input  lib/slash-command/registry/handlers/*
 * @output GENERATION_COMMAND_ENTRIES
 * @pos    生成、世界书、变量与提示词命令
 * @update 一旦我被更新，务必更新所属 README 与 PRD slash command 附录。
 */

import type { CommandEntry } from "./types";
import * as GenerationHandlers from "./handlers/generation";
import * as LoreHandlers from "./handlers/lore";
import * as SystemPromptHandlers from "./handlers/system-prompt";
import * as VariableHandlers from "./handlers/variables";

export const GENERATION_COMMAND_ENTRIES: CommandEntry[] = [
  ["sysname", SystemPromptHandlers.handleSystemName],
  ["sysgen", SystemPromptHandlers.handleSystemGenerate],
  ["reasoning-template", GenerationHandlers.handleReasoningTemplate],
  ["reasoning-preset", GenerationHandlers.handleReasoningTemplate],
  ["reasoning-formatting", GenerationHandlers.handleReasoningTemplate],
  ["setvar", VariableHandlers.handleSetVar],
  ["setchatvar", VariableHandlers.handleSetVar],
  ["setglobalvar", VariableHandlers.handleSetGlobalVar],
  ["getvar", VariableHandlers.handleGetVar],
  ["getchatvar", VariableHandlers.handleGetVar],
  ["getglobalvar", VariableHandlers.handleGetGlobalVar],
  ["delvar", VariableHandlers.handleDelVar],
  ["listvar", VariableHandlers.handleListVar],
  ["listchatvar", VariableHandlers.handleListVar],
  ["flushvar", VariableHandlers.handleFlushVar],
  ["flushchatvar", VariableHandlers.handleFlushVar],
  ["flushglobalvar", VariableHandlers.handleFlushGlobalVar],
  ["dumpvar", VariableHandlers.handleDumpVar],
  ["addvar", VariableHandlers.handleAddVar],
  ["addchatvar", VariableHandlers.handleAddVar],
  ["addglobalvar", VariableHandlers.handleAddGlobalVar],
  ["incvar", VariableHandlers.handleIncVar],
  ["incchatvar", VariableHandlers.handleIncVar],
  ["incglobalvar", VariableHandlers.handleIncGlobalVar],
  ["decvar", VariableHandlers.handleDecVar],
  ["decchatvar", VariableHandlers.handleDecVar],
  ["decglobalvar", VariableHandlers.handleDecGlobalVar],
  ["push", VariableHandlers.handlePush],
  ["getentry", GenerationHandlers.handleGetEntry],
  ["searchentry", GenerationHandlers.handleSearchEntry],
  ["setentry", GenerationHandlers.handleSetEntry],
  ["createentry", GenerationHandlers.handleCreateEntry],
  ["deleteentry", GenerationHandlers.handleDeleteEntry],
  ["delentry", GenerationHandlers.handleDeleteEntry],
  ["activateentry", GenerationHandlers.handleActivateEntry],
  ["listentries", GenerationHandlers.handleListEntries],
  ["worldbook", GenerationHandlers.handleWorldBook],
  ["wb", GenerationHandlers.handleWorldBook],
  ["world", LoreHandlers.handleWorld],
  ["getcharbook", LoreHandlers.handleGetCharLore],
  ["getcharlore", LoreHandlers.handleGetCharLore],
  ["getcharwi", LoreHandlers.handleGetCharLore],
  ["getchatbook", LoreHandlers.handleGetChatLore],
  ["getchatlore", LoreHandlers.handleGetChatLore],
  ["getchatwi", LoreHandlers.handleGetChatLore],
  ["getglobalbooks", LoreHandlers.handleGetGlobalLore],
  ["getgloballore", LoreHandlers.handleGetGlobalLore],
  ["getglobalwi", LoreHandlers.handleGetGlobalLore],
  ["getpersonabook", LoreHandlers.handleGetPersonaLore],
  ["getpersonalore", LoreHandlers.handleGetPersonaLore],
  ["getpersonawi", LoreHandlers.handleGetPersonaLore],
  ["getlorefield", LoreHandlers.handleGetLoreField],
  ["getentryfield", LoreHandlers.handleGetLoreField],
  ["getwifield", LoreHandlers.handleGetLoreField],
  ["setlorefield", LoreHandlers.handleSetLoreField],
  ["setentryfield", LoreHandlers.handleSetLoreField],
  ["setwifield", LoreHandlers.handleSetLoreField],
  ["wi-get-timed-effect", LoreHandlers.handleGetWorldInfoTimedEffect],
  ["wi-set-timed-effect", LoreHandlers.handleSetWorldInfoTimedEffect],
  ["findentry", LoreHandlers.handleFindLore],
  ["findlore", LoreHandlers.handleFindLore],
  ["findwi", LoreHandlers.handleFindLore],
  ["createlore", LoreHandlers.handleCreateLore],
  ["createwi", LoreHandlers.handleCreateLore],
  ["vector-threshold", LoreHandlers.handleVectorThreshold],
  ["vector-query", LoreHandlers.handleVectorQuery],
  ["vector-max-entries", LoreHandlers.handleVectorMaxEntries],
  ["vector-chats-state", LoreHandlers.handleVectorChatsState],
  ["vector-files-state", LoreHandlers.handleVectorFilesState],
  ["vector-worldinfo-state", LoreHandlers.handleVectorWorldInfoState],
  ["gen", GenerationHandlers.handleGen],
  ["generate", GenerationHandlers.handleGen],
  ["genraw", GenerationHandlers.handleGenRaw],
  ["genq", GenerationHandlers.handleGenQuiet],
  ["generatequiet", GenerationHandlers.handleGenQuiet],
  ["generate-stop", GenerationHandlers.handleGenerateStop],
  ["summarize", GenerationHandlers.handleSummarize],
  ["inject", GenerationHandlers.handleInject],
  ["activatelore", GenerationHandlers.handleActivateLore],
  ["imagine", GenerationHandlers.handleImagine],
  ["image", GenerationHandlers.handleImagine],
  ["img", GenerationHandlers.handleImagine],
  ["sd", GenerationHandlers.handleImagine],
  ["imagine-source", GenerationHandlers.handleImagineSource],
  ["img-source", GenerationHandlers.handleImagineSource],
  ["sd-source", GenerationHandlers.handleImagineSource],
  ["imagine-style", GenerationHandlers.handleImagineStyle],
  ["img-style", GenerationHandlers.handleImagineStyle],
  ["sd-style", GenerationHandlers.handleImagineStyle],
  ["imagine-comfy-workflow", GenerationHandlers.handleImagineComfyWorkflow],
  ["icw", GenerationHandlers.handleImagineComfyWorkflow],
  ["preset", GenerationHandlers.handlePreset],
  ["stop-strings", GenerationHandlers.handleStopStrings],
  ["stopping-strings", GenerationHandlers.handleStopStrings],
  ["custom-stopping-strings", GenerationHandlers.handleStopStrings],
  ["custom-stop-strings", GenerationHandlers.handleStopStrings],
  ["model", GenerationHandlers.handleModel],
  ["start-reply-with", GenerationHandlers.handleStartReplyWith],
  ["reroll-pick", GenerationHandlers.handleRerollPick],
  ["instruct", GenerationHandlers.handleInstruct],
  ["instruct-on", GenerationHandlers.handleInstructOn],
  ["instruct-off", GenerationHandlers.handleInstructOff],
  ["instruct-state", GenerationHandlers.handleInstructState],
  ["instruct-toggle", GenerationHandlers.handleInstructState],
  ["sysprompt", SystemPromptHandlers.handleSystemPrompt],
  ["system-prompt", SystemPromptHandlers.handleSystemPrompt],
  ["sysprompt-on", SystemPromptHandlers.handleSystemPromptOn],
  ["sysprompt-enable", SystemPromptHandlers.handleSystemPromptOn],
  ["sysprompt-off", SystemPromptHandlers.handleSystemPromptOff],
  ["sysprompt-disable", SystemPromptHandlers.handleSystemPromptOff],
  ["sysprompt-state", SystemPromptHandlers.handleSystemPromptState],
  ["sysprompt-toggle", SystemPromptHandlers.handleSystemPromptState],
  ["context", GenerationHandlers.handleContext],
  ["listpresets", GenerationHandlers.handleListPresets],
  ["getpromptentry", GenerationHandlers.handleGetPromptEntry],
  ["getpromptentries", GenerationHandlers.handleGetPromptEntry],
  ["setpromptentry", GenerationHandlers.handleSetPromptEntry],
  ["setpromptentries", GenerationHandlers.handleSetPromptEntry],
  ["regex", GenerationHandlers.handleRegex],
  ["regex-preset", GenerationHandlers.handleRegexPreset],
  ["regex-toggle", GenerationHandlers.handleRegexToggle],
  ["audio", GenerationHandlers.handleAudio],
  ["play", GenerationHandlers.handlePlay],
  ["stop", GenerationHandlers.handleStop],
];
