/**
 * @input  lib/slash-command/registry/handlers/*
 * @output FOUNDATION_COMMAND_ENTRIES
 * @pos    基础、UI、工具与数据命令
 * @update 一旦我被更新，务必更新所属 README 与 PRD slash command 附录。
 */

import type { CommandEntry } from "./types";
import * as CoreHandlers from "./handlers/core";
import * as UiHandlers from "./handlers/ui";
import * as UtilityHandlers from "./handlers/utility";
import * as NotePersonaHandlers from "./handlers/note-persona";
import * as ProfilePromptHandlers from "./handlers/profile-prompt";
import * as SecretHandlers from "./handlers/secrets";
import * as ToolingHandlers from "./handlers/tooling";
import * as ApiHandlers from "./handlers/api";
import * as FuzzyHandlers from "./handlers/fuzzy";
import * as DataBankHandlers from "./handlers/data-bank";

export const FOUNDATION_COMMAND_ENTRIES: CommandEntry[] = [
  ["send", CoreHandlers.handleSend],
  ["trigger", CoreHandlers.handleTrigger],
  ["sendas", CoreHandlers.handleSendAs],
  ["sys", CoreHandlers.handleSys],
  ["narrator", CoreHandlers.handleSys],
  ["nar", CoreHandlers.handleSys],
  ["narrate", CoreHandlers.handleNarrate],
  ["speak", CoreHandlers.handleNarrate],
  ["tts", CoreHandlers.handleNarrate],
  ["impersonate", CoreHandlers.handleImpersonate],
  ["imp", CoreHandlers.handleImpersonate],
  ["continue", CoreHandlers.handleContinue],
  ["cont", CoreHandlers.handleContinue],
  ["swipe", CoreHandlers.handleSwipe],
  ["comment", CoreHandlers.handleSys],
  ["checkpoint-create", CoreHandlers.handleCheckpointCreate],
  ["branch-create", CoreHandlers.handleBranchCreate],
  ["checkpoint-get", CoreHandlers.handleCheckpointGet],
  ["checkpoint-list", CoreHandlers.handleCheckpointList],
  ["checkpoint-go", CoreHandlers.handleCheckpointGo],
  ["checkpoint-exit", CoreHandlers.handleCheckpointExit],
  ["checkpoint-parent", CoreHandlers.handleCheckpointParent],
  ["panels", UiHandlers.handlePanels],
  ["togglepanels", UiHandlers.handlePanels],
  ["bg", UiHandlers.handleBg],
  ["background", UiHandlers.handleBg],
  ["lockbg", UiHandlers.handleLockBg],
  ["bglock", UiHandlers.handleLockBg],
  ["unlockbg", UiHandlers.handleUnlockBg],
  ["bgunlock", UiHandlers.handleUnlockBg],
  ["autobg", UiHandlers.handleAutoBg],
  ["bgauto", UiHandlers.handleAutoBg],
  ["bgcol", UiHandlers.handleBgCol],
  ["bubble", UiHandlers.handleBubble],
  ["bubbles", UiHandlers.handleBubble],
  ["flat", UiHandlers.handleFlat],
  ["default", UiHandlers.handleFlat],
  ["single", UiHandlers.handleStory],
  ["story", UiHandlers.handleStory],
  ["theme", UiHandlers.handleTheme],
  ["movingui", UiHandlers.handleMovingUi],
  ["css-var", UiHandlers.handleCssVar],
  ["buttons", UiHandlers.handleButtons],
  ["vn", UiHandlers.handleVn],
  ["resetpanels", UiHandlers.handleResetPanels],
  ["resetui", UiHandlers.handleResetPanels],
  ["caption", UiHandlers.handleCaption],
  ["beep", UiHandlers.handleBeep],
  ["ding", UiHandlers.handleBeep],
  ["popup", UiHandlers.handlePopup],
  ["pick-icon", UiHandlers.handlePickIcon],
  ["run", UtilityHandlers.handleRun],
  ["show-gallery", UtilityHandlers.handleShowGallery],
  ["sg", UtilityHandlers.handleShowGallery],
  ["call", UtilityHandlers.handleRun],
  ["exec", UtilityHandlers.handleRun],
  ["closure-serialize", UtilityHandlers.handleClosureSerialize],
  ["closure-deserialize", UtilityHandlers.handleClosureDeserialize],
  ["lock", UtilityHandlers.handleLock],
  ["bind", UtilityHandlers.handleLock],
  ["persona-lock", NotePersonaHandlers.handlePersonaLock],
  ["persona-set", NotePersonaHandlers.handlePersonaSet],
  ["persona", NotePersonaHandlers.handlePersonaSet],
  ["persona-sync", NotePersonaHandlers.handlePersonaSync],
  ["sync", NotePersonaHandlers.handlePersonaSync],
  ["note", NotePersonaHandlers.handleNote],
  ["note-depth", NotePersonaHandlers.handleNoteDepth],
  ["depth", NotePersonaHandlers.handleNoteDepth],
  ["note-frequency", NotePersonaHandlers.handleNoteFrequency],
  ["note-freq", NotePersonaHandlers.handleNoteFrequency],
  ["freq", NotePersonaHandlers.handleNoteFrequency],
  ["note-position", NotePersonaHandlers.handleNotePosition],
  ["note-pos", NotePersonaHandlers.handleNotePosition],
  ["pos", NotePersonaHandlers.handleNotePosition],
  ["note-role", NotePersonaHandlers.handleNoteRole],
  ["profile", ProfilePromptHandlers.handleProfile],
  ["profile-list", ProfilePromptHandlers.handleProfileList],
  ["profile-create", ProfilePromptHandlers.handleProfileCreate],
  ["profile-update", ProfilePromptHandlers.handleProfileUpdate],
  ["profile-get", ProfilePromptHandlers.handleProfileGet],
  ["trimtokens", UtilityHandlers.handleTrimTokens],
  ["trimstart", UtilityHandlers.handleTrimStart],
  ["trimend", UtilityHandlers.handleTrimEnd],
  ["sort", UtilityHandlers.handleSort],
  ["tokens", UtilityHandlers.handleTokens],
  ["count", UtilityHandlers.handleCount],
  ["reload-page", UtilityHandlers.handleReloadPage],
  ["delay", UtilityHandlers.handleDelay],
  ["wait", UtilityHandlers.handleDelay],
  ["sleep", UtilityHandlers.handleDelay],
  ["secret-id", SecretHandlers.handleSecretId],
  ["secret-rotate", SecretHandlers.handleSecretId],
  ["secret-delete", SecretHandlers.handleSecretDelete],
  ["secret-write", SecretHandlers.handleSecretWrite],
  ["secret-rename", SecretHandlers.handleSecretRename],
  ["secret-read", SecretHandlers.handleSecretRead],
  ["secret-find", SecretHandlers.handleSecretRead],
  ["secret-get", SecretHandlers.handleSecretRead],
  ["is-mobile", UtilityHandlers.handleIsMobile],
  ["import", UtilityHandlers.handleImport],
  ["tools-list", ToolingHandlers.handleToolList],
  ["tool-list", ToolingHandlers.handleToolList],
  ["tools-invoke", ToolingHandlers.handleToolInvoke],
  ["tool-invoke", ToolingHandlers.handleToolInvoke],
  ["tools-register", ToolingHandlers.handleToolRegister],
  ["tool-register", ToolingHandlers.handleToolRegister],
  ["tools-unregister", ToolingHandlers.handleToolUnregister],
  ["tool-unregister", ToolingHandlers.handleToolUnregister],
  ["list-gallery", UtilityHandlers.handleListGallery],
  ["lg", UtilityHandlers.handleListGallery],
  ["clipboard-get", UtilityHandlers.handleClipboardGet],
  ["clipboard-set", UtilityHandlers.handleClipboardSet],
  ["data-bank", DataBankHandlers.handleDataBank],
  ["databank", DataBankHandlers.handleDataBank],
  ["db", DataBankHandlers.handleDataBank],
  ["data-bank-list", DataBankHandlers.handleDataBankList],
  ["databank-list", DataBankHandlers.handleDataBankList],
  ["db-list", DataBankHandlers.handleDataBankList],
  ["data-bank-get", DataBankHandlers.handleDataBankGet],
  ["databank-get", DataBankHandlers.handleDataBankGet],
  ["db-get", DataBankHandlers.handleDataBankGet],
  ["data-bank-add", DataBankHandlers.handleDataBankAdd],
  ["databank-add", DataBankHandlers.handleDataBankAdd],
  ["db-add", DataBankHandlers.handleDataBankAdd],
  ["data-bank-update", DataBankHandlers.handleDataBankUpdate],
  ["databank-update", DataBankHandlers.handleDataBankUpdate],
  ["db-update", DataBankHandlers.handleDataBankUpdate],
  ["data-bank-delete", DataBankHandlers.handleDataBankDelete],
  ["databank-delete", DataBankHandlers.handleDataBankDelete],
  ["db-delete", DataBankHandlers.handleDataBankDelete],
  ["data-bank-disable", DataBankHandlers.handleDataBankDisable],
  ["databank-disable", DataBankHandlers.handleDataBankDisable],
  ["db-disable", DataBankHandlers.handleDataBankDisable],
  ["data-bank-enable", DataBankHandlers.handleDataBankEnable],
  ["databank-enable", DataBankHandlers.handleDataBankEnable],
  ["db-enable", DataBankHandlers.handleDataBankEnable],
  ["data-bank-ingest", DataBankHandlers.handleDataBankIngest],
  ["databank-ingest", DataBankHandlers.handleDataBankIngest],
  ["db-ingest", DataBankHandlers.handleDataBankIngest],
  ["data-bank-purge", DataBankHandlers.handleDataBankPurge],
  ["databank-purge", DataBankHandlers.handleDataBankPurge],
  ["db-purge", DataBankHandlers.handleDataBankPurge],
  ["data-bank-search", DataBankHandlers.handleDataBankSearch],
  ["databank-search", DataBankHandlers.handleDataBankSearch],
  ["db-search", DataBankHandlers.handleDataBankSearch],
  ["api", ApiHandlers.handleApi],
  ["api-url", ApiHandlers.handleApiUrl],
  ["server", ApiHandlers.handleApiUrl],
  ["proxy", ApiHandlers.handleProxy],
  ["fuzzy", FuzzyHandlers.handleFuzzy],
  ["?", CoreHandlers.handleHelp],
  ["help", CoreHandlers.handleHelp],
  ["echo", CoreHandlers.handleEcho],
  ["pass", CoreHandlers.handlePass],
  ["return", CoreHandlers.handleReturn],
  ["tag-add", ToolingHandlers.handleTagAdd],
  ["tag-remove", ToolingHandlers.handleTagRemove],
  ["tag-exists", ToolingHandlers.handleTagExists],
  ["tag-list", ToolingHandlers.handleTagList],
  ["prompt", ProfilePromptHandlers.handlePrompt],
  ["prompt-post-processing", ProfilePromptHandlers.handlePromptPostProcessing],
  ["ppp", ProfilePromptHandlers.handlePromptPostProcessing],
];
