/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                         Slash Command Registry                             ║
 * ║                                                                            ║
 * ║  好品味：用 Map 消灭 switch/case，模块化组织命令处理器                        ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import type { CommandHandler } from "./types";

// 导入所有命令处理器
import * as CoreHandlers from "./handlers/core";
import * as VariableHandlers from "./handlers/variables";
import * as MessageHandlers from "./handlers/messages";
import * as CharacterHandlers from "./handlers/characters";
import * as GenerationHandlers from "./handlers/generation";
import * as OperatorHandlers from "./handlers/operators";
import * as JSSlashRunnerHandlers from "./handlers/js-slash-runner";
import * as ApiHandlers from "./handlers/api";
import * as FuzzyHandlers from "./handlers/fuzzy";
import * as ChatHandlers from "./handlers/chat";
import * as UtilityHandlers from "./handlers/utility";
import * as UiHandlers from "./handlers/ui";
import * as LoreHandlers from "./handlers/lore";
import * as DataBankHandlers from "./handlers/data-bank";
import * as ExpressionHandlers from "./handlers/expression";
import * as ExtensionHandlers from "./handlers/extensions";
import * as NotePersonaHandlers from "./handlers/note-persona";
import * as ProfilePromptHandlers from "./handlers/profile-prompt";
import * as QuickReplyHandlers from "./handlers/quick-reply";
import * as SecretHandlers from "./handlers/secrets";
import * as SystemPromptHandlers from "./handlers/system-prompt";
import * as ToolingHandlers from "./handlers/tooling";

/* ═══════════════════════════════════════════════════════════════════════════
   命令注册表 - 好品味：Map + 模块化
   ═══════════════════════════════════════════════════════════════════════════ */

export const COMMAND_REGISTRY: Map<string, CommandHandler> = new Map([
  // ─── 核心消息命令 ───
  ["send", CoreHandlers.handleSend],
  ["trigger", CoreHandlers.handleTrigger],
  ["sendas", CoreHandlers.handleSendAs],
  ["sys", CoreHandlers.handleSys],
  ["narrator", CoreHandlers.handleSys],
  ["nar", CoreHandlers.handleSys],
  ["sysname", SystemPromptHandlers.handleSystemName],
  ["sysgen", SystemPromptHandlers.handleSystemGenerate],
  ["narrate", CoreHandlers.handleNarrate],
  ["impersonate", CoreHandlers.handleImpersonate],
  ["imp", CoreHandlers.handleImpersonate],
  ["continue", CoreHandlers.handleContinue],
  ["cont", CoreHandlers.handleContinue],
  ["swipe", CoreHandlers.handleSwipe],
  ["comment", CoreHandlers.handleSys],
  ["checkpoint-create", CoreHandlers.handleCheckpointCreate],
  ["branch-create", CoreHandlers.handleBranchCreate],
  ["checkpoint-get", CoreHandlers.handleCheckpointGet],
  ["checkpoint-list", CoreHandlers.handleCheckpointList],
  ["checkpoint-go", CoreHandlers.handleCheckpointGo],
  ["checkpoint-exit", CoreHandlers.handleCheckpointExit],
  ["checkpoint-parent", CoreHandlers.handleCheckpointParent],
  ["panels", UiHandlers.handlePanels],
  ["togglepanels", UiHandlers.handlePanels],
  ["bg", UiHandlers.handleBg],
  ["background", UiHandlers.handleBg],
  ["lockbg", UiHandlers.handleLockBg],
  ["bglock", UiHandlers.handleLockBg],
  ["unlockbg", UiHandlers.handleUnlockBg],
  ["bgunlock", UiHandlers.handleUnlockBg],
  ["autobg", UiHandlers.handleAutoBg],
  ["bgauto", UiHandlers.handleAutoBg],
  ["bgcol", UiHandlers.handleBgCol],
  ["bubble", UiHandlers.handleBubble],
  ["bubbles", UiHandlers.handleBubble],
  ["flat", UiHandlers.handleFlat],
  ["default", UiHandlers.handleFlat],
  ["single", UiHandlers.handleStory],
  ["story", UiHandlers.handleStory],
  ["theme", UiHandlers.handleTheme],
  ["movingui", UiHandlers.handleMovingUi],
  ["css-var", UiHandlers.handleCssVar],
  ["buttons", UiHandlers.handleButtons],
  ["vn", UiHandlers.handleVn],
  ["resetpanels", UiHandlers.handleResetPanels],
  ["resetui", UiHandlers.handleResetPanels],
  ["caption", UiHandlers.handleCaption],
  ["beep", UiHandlers.handleBeep],
  ["ding", UiHandlers.handleBeep],
  ["popup", UiHandlers.handlePopup],
  ["pick-icon", UiHandlers.handlePickIcon],
  ["run", UtilityHandlers.handleRun],
  ["call", UtilityHandlers.handleRun],
  ["exec", UtilityHandlers.handleRun],
  ["closure-serialize", UtilityHandlers.handleClosureSerialize],
  ["closure-deserialize", UtilityHandlers.handleClosureDeserialize],
  ["lock", UtilityHandlers.handleLock],
  ["bind", UtilityHandlers.handleLock],
  ["persona-lock", NotePersonaHandlers.handlePersonaLock],
  ["persona-set", NotePersonaHandlers.handlePersonaSet],
  ["persona", NotePersonaHandlers.handlePersonaSet],
  ["persona-sync", NotePersonaHandlers.handlePersonaSync],
  ["sync", NotePersonaHandlers.handlePersonaSync],
  ["note", NotePersonaHandlers.handleNote],
  ["note-depth", NotePersonaHandlers.handleNoteDepth],
  ["depth", NotePersonaHandlers.handleNoteDepth],
  ["note-frequency", NotePersonaHandlers.handleNoteFrequency],
  ["note-freq", NotePersonaHandlers.handleNoteFrequency],
  ["freq", NotePersonaHandlers.handleNoteFrequency],
  ["note-position", NotePersonaHandlers.handleNotePosition],
  ["note-pos", NotePersonaHandlers.handleNotePosition],
  ["pos", NotePersonaHandlers.handleNotePosition],
  ["note-role", NotePersonaHandlers.handleNoteRole],
  ["profile", ProfilePromptHandlers.handleProfile],
  ["profile-list", ProfilePromptHandlers.handleProfileList],
  ["profile-create", ProfilePromptHandlers.handleProfileCreate],
  ["profile-update", ProfilePromptHandlers.handleProfileUpdate],
  ["profile-get", ProfilePromptHandlers.handleProfileGet],
  ["trimtokens", UtilityHandlers.handleTrimTokens],
  ["count", UtilityHandlers.handleCount],
  ["reload-page", UtilityHandlers.handleReloadPage],
  ["delay", UtilityHandlers.handleDelay],
  ["wait", UtilityHandlers.handleDelay],
  ["sleep", UtilityHandlers.handleDelay],
  ["secret-id", SecretHandlers.handleSecretId],
  ["secret-rotate", SecretHandlers.handleSecretId],
  ["secret-delete", SecretHandlers.handleSecretDelete],
  ["secret-write", SecretHandlers.handleSecretWrite],
  ["secret-rename", SecretHandlers.handleSecretRename],
  ["secret-read", SecretHandlers.handleSecretRead],
  ["secret-find", SecretHandlers.handleSecretRead],
  ["secret-get", SecretHandlers.handleSecretRead],
  ["is-mobile", UtilityHandlers.handleIsMobile],
  ["import", UtilityHandlers.handleImport],
  ["tools-list", ToolingHandlers.handleToolList],
  ["tool-list", ToolingHandlers.handleToolList],
  ["tools-invoke", ToolingHandlers.handleToolInvoke],
  ["tool-invoke", ToolingHandlers.handleToolInvoke],
  ["list-gallery", UtilityHandlers.handleListGallery],
  ["lg", UtilityHandlers.handleListGallery],
  ["clipboard-get", UtilityHandlers.handleClipboardGet],
  ["clipboard-set", UtilityHandlers.handleClipboardSet],
  ["data-bank", DataBankHandlers.handleDataBank],
  ["databank", DataBankHandlers.handleDataBank],
  ["db", DataBankHandlers.handleDataBank],
  ["data-bank-list", DataBankHandlers.handleDataBankList],
  ["databank-list", DataBankHandlers.handleDataBankList],
  ["db-list", DataBankHandlers.handleDataBankList],
  ["data-bank-get", DataBankHandlers.handleDataBankGet],
  ["databank-get", DataBankHandlers.handleDataBankGet],
  ["db-get", DataBankHandlers.handleDataBankGet],
  ["data-bank-add", DataBankHandlers.handleDataBankAdd],
  ["databank-add", DataBankHandlers.handleDataBankAdd],
  ["db-add", DataBankHandlers.handleDataBankAdd],
  ["data-bank-update", DataBankHandlers.handleDataBankUpdate],
  ["databank-update", DataBankHandlers.handleDataBankUpdate],
  ["db-update", DataBankHandlers.handleDataBankUpdate],
  ["data-bank-delete", DataBankHandlers.handleDataBankDelete],
  ["databank-delete", DataBankHandlers.handleDataBankDelete],
  ["db-delete", DataBankHandlers.handleDataBankDelete],
  ["data-bank-disable", DataBankHandlers.handleDataBankDisable],
  ["databank-disable", DataBankHandlers.handleDataBankDisable],
  ["db-disable", DataBankHandlers.handleDataBankDisable],
  ["data-bank-enable", DataBankHandlers.handleDataBankEnable],
  ["databank-enable", DataBankHandlers.handleDataBankEnable],
  ["db-enable", DataBankHandlers.handleDataBankEnable],
  ["data-bank-ingest", DataBankHandlers.handleDataBankIngest],
  ["databank-ingest", DataBankHandlers.handleDataBankIngest],
  ["db-ingest", DataBankHandlers.handleDataBankIngest],
  ["data-bank-purge", DataBankHandlers.handleDataBankPurge],
  ["databank-purge", DataBankHandlers.handleDataBankPurge],
  ["db-purge", DataBankHandlers.handleDataBankPurge],
  ["data-bank-search", DataBankHandlers.handleDataBankSearch],
  ["databank-search", DataBankHandlers.handleDataBankSearch],
  ["db-search", DataBankHandlers.handleDataBankSearch],
  ["api", ApiHandlers.handleApi],
  ["api-url", ApiHandlers.handleApiUrl],
  ["server", ApiHandlers.handleApiUrl],
  ["fuzzy", FuzzyHandlers.handleFuzzy],
  ["chat-manager", ChatHandlers.handleChatManager],
  ["chat-history", ChatHandlers.handleChatManager],
  ["manage-chats", ChatHandlers.handleChatManager],
  ["chat-reload", ChatHandlers.handleChatReload],
  ["newchat", ChatHandlers.handleNewChat],
  ["closechat", ChatHandlers.handleCloseChat],
  ["getchatname", ChatHandlers.handleGetChatName],
  ["renamechat", ChatHandlers.handleRenameChat],
  ["setinput", ChatHandlers.handleSetInput],
  ["input", ChatHandlers.handleSetInput],
  ["forcesave", ChatHandlers.handleForceSave],
  ["hide", ChatHandlers.handleHide],
  ["unhide", ChatHandlers.handleUnhide],
  ["member-get", ChatHandlers.handleGetMember],
  ["getmember", ChatHandlers.handleGetMember],
  ["memberget", ChatHandlers.handleGetMember],
  ["member-add", ChatHandlers.handleAddMember],
  ["addmember", ChatHandlers.handleAddMember],
  ["memberadd", ChatHandlers.handleAddMember],
  ["member-remove", ChatHandlers.handleRemoveMember],
  ["removemember", ChatHandlers.handleRemoveMember],
  ["memberremove", ChatHandlers.handleRemoveMember],
  ["member-up", ChatHandlers.handleMoveMemberUp],
  ["upmember", ChatHandlers.handleMoveMemberUp],
  ["memberup", ChatHandlers.handleMoveMemberUp],
  ["member-down", ChatHandlers.handleMoveMemberDown],
  ["downmember", ChatHandlers.handleMoveMemberDown],
  ["memberdown", ChatHandlers.handleMoveMemberDown],
  ["member-peek", ChatHandlers.handlePeekMember],
  ["peek", ChatHandlers.handlePeekMember],
  ["memberpeek", ChatHandlers.handlePeekMember],
  ["peekmember", ChatHandlers.handlePeekMember],
  ["member-count", ChatHandlers.handleCountMember],
  ["countmember", ChatHandlers.handleCountMember],
  ["membercount", ChatHandlers.handleCountMember],
  ["member-disable", ChatHandlers.handleDisableMember],
  ["disable", ChatHandlers.handleDisableMember],
  ["disablemember", ChatHandlers.handleDisableMember],
  ["memberdisable", ChatHandlers.handleDisableMember],
  ["member-enable", ChatHandlers.handleEnableMember],
  ["enable", ChatHandlers.handleEnableMember],
  ["enablemember", ChatHandlers.handleEnableMember],
  ["memberenable", ChatHandlers.handleEnableMember],
  ["addswipe", ChatHandlers.handleAddSwipe],
  ["swipeadd", ChatHandlers.handleAddSwipe],
  ["reasoning-get", ChatHandlers.handleGetReasoning],
  ["get-reasoning", ChatHandlers.handleGetReasoning],
  ["reasoning-set", ChatHandlers.handleSetReasoning],
  ["set-reasoning", ChatHandlers.handleSetReasoning],
  ["reasoning-parse", ChatHandlers.handleReasoningParse],
  ["parse-reasoning", ChatHandlers.handleReasoningParse],
  ["reasoning-template", GenerationHandlers.handleReasoningTemplate],
  ["reasoning-preset", GenerationHandlers.handleReasoningTemplate],
  ["reasoning-formatting", GenerationHandlers.handleReasoningTemplate],
  ["listinjects", ChatHandlers.handleListInjects],
  ["flushinject", ChatHandlers.handleFlushInjects],
  ["flushinjects", ChatHandlers.handleFlushInjects],
  ["chat-jump", ChatHandlers.handleChatJump],
  ["chat-scrollto", ChatHandlers.handleChatJump],
  ["chat-render", ChatHandlers.handleChatRender],
  ["cut", ChatHandlers.handleCut],
  ["delchat", ChatHandlers.handleDelChat],
  ["delmode", ChatHandlers.handleDelMode],
  ["delete", ChatHandlers.handleDelete],
  ["delname", ChatHandlers.handleDelName],
  ["cancel", ChatHandlers.handleDelName],
  ["delswipe", ChatHandlers.handleDelSwipe],
  ["swipedel", ChatHandlers.handleDelSwipe],
  ["expression-set", ExpressionHandlers.handleExpressionSet],
  ["sprite", ExpressionHandlers.handleExpressionSet],
  ["emote", ExpressionHandlers.handleExpressionSet],
  ["expression-folder-override", ExpressionHandlers.handleExpressionFolderOverride],
  ["spriteoverride", ExpressionHandlers.handleExpressionFolderOverride],
  ["costume", ExpressionHandlers.handleExpressionFolderOverride],
  ["expression-last", ExpressionHandlers.handleExpressionLast],
  ["lastsprite", ExpressionHandlers.handleExpressionLast],
  ["expression-list", ExpressionHandlers.handleExpressionList],
  ["expressions", ExpressionHandlers.handleExpressionList],
  ["expression-classify", ExpressionHandlers.handleExpressionClassify],
  ["classify", ExpressionHandlers.handleExpressionClassify],
  ["extension-enable", ExtensionHandlers.handleExtensionEnable],
  ["extension-disable", ExtensionHandlers.handleExtensionDisable],
  ["extension-toggle", ExtensionHandlers.handleExtensionToggle],
  ["extension-state", ExtensionHandlers.handleExtensionState],
  ["extension-exists", ExtensionHandlers.handleExtensionExists],
  ["extension-installed", ExtensionHandlers.handleExtensionExists],
  ["qr", QuickReplyHandlers.handleQr],
  ["qr-set", QuickReplyHandlers.handleQrSet],
  ["qr-set-on", QuickReplyHandlers.handleQrSetOn],
  ["qr-set-off", QuickReplyHandlers.handleQrSetOff],
  ["qr-chat-set", QuickReplyHandlers.handleQrChatSet],
  ["qr-chat-set-on", QuickReplyHandlers.handleQrChatSetOn],
  ["qr-chat-set-off", QuickReplyHandlers.handleQrChatSetOff],
  ["qr-set-list", QuickReplyHandlers.handleQrSetList],
  ["qr-list", QuickReplyHandlers.handleQrList],
  ["qr-get", QuickReplyHandlers.handleQrGet],
  ["qr-create", QuickReplyHandlers.handleQrCreate],
  ["qr-update", QuickReplyHandlers.handleQrUpdate],
  ["qr-delete", QuickReplyHandlers.handleQrDelete],
  ["qr-contextadd", QuickReplyHandlers.handleQrContextAdd],
  ["qr-contextdel", QuickReplyHandlers.handleQrContextDel],
  ["qr-contextclear", QuickReplyHandlers.handleQrContextClear],
  ["qr-set-create", QuickReplyHandlers.handleQrSetCreate],
  ["qr-presetadd", QuickReplyHandlers.handleQrSetCreate],
  ["qr-set-update", QuickReplyHandlers.handleQrSetUpdate],
  ["qr-presetupdate", QuickReplyHandlers.handleQrSetUpdate],
  ["qr-set-delete", QuickReplyHandlers.handleQrSetDelete],
  ["qr-presetdelete", QuickReplyHandlers.handleQrSetDelete],

  // ─── 工具命令 ───
  ["?", CoreHandlers.handleHelp],
  ["help", CoreHandlers.handleHelp],
  ["echo", CoreHandlers.handleEcho],
  ["pass", CoreHandlers.handlePass],
  ["return", CoreHandlers.handleReturn],

  // ─── 变量命令 ───
  ["setvar", VariableHandlers.handleSetVar],
  ["setchatvar", VariableHandlers.handleSetVar],
  ["setglobalvar", VariableHandlers.handleSetGlobalVar],
  ["getvar", VariableHandlers.handleGetVar],
  ["getchatvar", VariableHandlers.handleGetVar],
  ["getglobalvar", VariableHandlers.handleGetGlobalVar],
  ["delvar", VariableHandlers.handleDelVar],
  ["listvar", VariableHandlers.handleListVar],
  ["listchatvar", VariableHandlers.handleListVar],
  ["flushvar", VariableHandlers.handleFlushVar],
  ["flushchatvar", VariableHandlers.handleFlushVar],
  ["flushglobalvar", VariableHandlers.handleFlushGlobalVar],
  ["dumpvar", VariableHandlers.handleDumpVar],
  ["addvar", VariableHandlers.handleAddVar],
  ["addchatvar", VariableHandlers.handleAddVar],
  ["addglobalvar", VariableHandlers.handleAddGlobalVar],
  ["incvar", VariableHandlers.handleIncVar],
  ["incchatvar", VariableHandlers.handleIncVar],
  ["incglobalvar", VariableHandlers.handleIncGlobalVar],
  ["decvar", VariableHandlers.handleDecVar],
  ["decchatvar", VariableHandlers.handleDecVar],
  ["decglobalvar", VariableHandlers.handleDecGlobalVar],
  ["push", VariableHandlers.handlePush],

  // ─── 消息管理命令 ───
  ["getmessage", MessageHandlers.handleGetMessage],
  ["getmes", MessageHandlers.handleGetMessage],
  ["setmessage", MessageHandlers.handleEditMessage],
  ["setmes", MessageHandlers.handleEditMessage],
  ["editmessage", MessageHandlers.handleEditMessage],
  ["editmes", MessageHandlers.handleEditMessage],
  ["edit", MessageHandlers.handleEditMessage],
  ["delmessage", MessageHandlers.handleDelMessage],
  ["delmes", MessageHandlers.handleDelMessage],
  ["del", MessageHandlers.handleDelMessage],
  ["messages", MessageHandlers.handleMessages],
  ["mes", MessageHandlers.handleMessages],
  ["message", MessageHandlers.handleMessages],
  ["message-role", MessageHandlers.handleMessageRole],
  ["message-name", MessageHandlers.handleMessageName],
  ["name", MessageHandlers.handleMessageName],
  ["messagecount", MessageHandlers.handleMessageCount],
  ["mescount", MessageHandlers.handleMessageCount],
  ["char", CharacterHandlers.handleCharacter],
  ["character", CharacterHandlers.handleCharacter],
  ["go", CharacterHandlers.handleCharacter],
  ["char-find", CharacterHandlers.handleCharacterFind],
  ["findchar", CharacterHandlers.handleCharacterFind],
  ["rename-char", CharacterHandlers.handleRenameCharacter],
  ["dupe", CharacterHandlers.handleDupe],
  ["ask", CharacterHandlers.handleAsk],
  ["tag-add", ToolingHandlers.handleTagAdd],
  ["tag-remove", ToolingHandlers.handleTagRemove],
  ["tag-exists", ToolingHandlers.handleTagExists],
  ["tag-list", ToolingHandlers.handleTagList],

  // ─── World Book 命令 ───
  ["getentry", GenerationHandlers.handleGetEntry],
  ["searchentry", GenerationHandlers.handleSearchEntry],
  ["setentry", GenerationHandlers.handleSetEntry],
  ["createentry", GenerationHandlers.handleCreateEntry],
  ["deleteentry", GenerationHandlers.handleDeleteEntry],
  ["delentry", GenerationHandlers.handleDeleteEntry],
  ["activateentry", GenerationHandlers.handleActivateEntry],
  ["listentries", GenerationHandlers.handleListEntries],
  ["worldbook", GenerationHandlers.handleWorldBook],
  ["wb", GenerationHandlers.handleWorldBook],
  ["world", LoreHandlers.handleWorld],
  ["getcharbook", LoreHandlers.handleGetCharLore],
  ["getcharlore", LoreHandlers.handleGetCharLore],
  ["getcharwi", LoreHandlers.handleGetCharLore],
  ["getchatbook", LoreHandlers.handleGetChatLore],
  ["getchatlore", LoreHandlers.handleGetChatLore],
  ["getchatwi", LoreHandlers.handleGetChatLore],
  ["getglobalbooks", LoreHandlers.handleGetGlobalLore],
  ["getgloballore", LoreHandlers.handleGetGlobalLore],
  ["getglobalwi", LoreHandlers.handleGetGlobalLore],
  ["getpersonabook", LoreHandlers.handleGetPersonaLore],
  ["getpersonalore", LoreHandlers.handleGetPersonaLore],
  ["getpersonawi", LoreHandlers.handleGetPersonaLore],
  ["getlorefield", LoreHandlers.handleGetLoreField],
  ["getentryfield", LoreHandlers.handleGetLoreField],
  ["getwifield", LoreHandlers.handleGetLoreField],
  ["setlorefield", LoreHandlers.handleSetLoreField],
  ["setentryfield", LoreHandlers.handleSetLoreField],
  ["setwifield", LoreHandlers.handleSetLoreField],
  ["findentry", LoreHandlers.handleFindLore],
  ["findlore", LoreHandlers.handleFindLore],
  ["findwi", LoreHandlers.handleFindLore],
  ["createlore", LoreHandlers.handleCreateLore],
  ["createwi", LoreHandlers.handleCreateLore],
  ["vector-worldinfo-state", LoreHandlers.handleVectorWorldInfoState],

  // ─── 生成命令 ───
  ["gen", GenerationHandlers.handleGen],
  ["generate", GenerationHandlers.handleGen],
  ["genraw", GenerationHandlers.handleGenRaw],
  ["genq", GenerationHandlers.handleGenQuiet],
  ["generatequiet", GenerationHandlers.handleGenQuiet],
  ["generate-stop", GenerationHandlers.handleGenerateStop],
  ["inject", GenerationHandlers.handleInject],
  ["activatelore", GenerationHandlers.handleActivateLore],
  ["imagine", GenerationHandlers.handleImagine],
  ["image", GenerationHandlers.handleImagine],
  ["img", GenerationHandlers.handleImagine],
  ["imagine-source", GenerationHandlers.handleImagineSource],
  ["img-source", GenerationHandlers.handleImagineSource],
  ["imagine-style", GenerationHandlers.handleImagineStyle],
  ["img-style", GenerationHandlers.handleImagineStyle],
  ["imagine-comfy-workflow", GenerationHandlers.handleImagineComfyWorkflow],
  ["icw", GenerationHandlers.handleImagineComfyWorkflow],

  // ─── Preset 命令 ───
  ["preset", GenerationHandlers.handlePreset],
  ["stop-strings", GenerationHandlers.handleStopStrings],
  ["stopping-strings", GenerationHandlers.handleStopStrings],
  ["custom-stopping-strings", GenerationHandlers.handleStopStrings],
  ["custom-stop-strings", GenerationHandlers.handleStopStrings],
  ["model", GenerationHandlers.handleModel],
  ["instruct", GenerationHandlers.handleInstruct],
  ["instruct-on", GenerationHandlers.handleInstructOn],
  ["instruct-off", GenerationHandlers.handleInstructOff],
  ["instruct-state", GenerationHandlers.handleInstructState],
  ["instruct-toggle", GenerationHandlers.handleInstructState],
  ["sysprompt", SystemPromptHandlers.handleSystemPrompt],
  ["system-prompt", SystemPromptHandlers.handleSystemPrompt],
  ["sysprompt-on", SystemPromptHandlers.handleSystemPromptOn],
  ["sysprompt-enable", SystemPromptHandlers.handleSystemPromptOn],
  ["sysprompt-off", SystemPromptHandlers.handleSystemPromptOff],
  ["sysprompt-disable", SystemPromptHandlers.handleSystemPromptOff],
  ["sysprompt-state", SystemPromptHandlers.handleSystemPromptState],
  ["sysprompt-toggle", SystemPromptHandlers.handleSystemPromptState],
  ["context", GenerationHandlers.handleContext],
  ["listpresets", GenerationHandlers.handleListPresets],
  ["getpromptentry", GenerationHandlers.handleGetPromptEntry],
  ["getpromptentries", GenerationHandlers.handleGetPromptEntry],
  ["setpromptentry", GenerationHandlers.handleSetPromptEntry],
  ["setpromptentries", GenerationHandlers.handleSetPromptEntry],
  ["prompt", ProfilePromptHandlers.handlePrompt],
  ["prompt-post-processing", ProfilePromptHandlers.handlePromptPostProcessing],
  ["ppp", ProfilePromptHandlers.handlePromptPostProcessing],

  // ─── Regex 命令 ───
  ["regex", GenerationHandlers.handleRegex],
  ["regex-preset", GenerationHandlers.handleRegexPreset],
  ["regex-toggle", GenerationHandlers.handleRegexToggle],

  // ─── Audio 命令 ───
  ["audio", GenerationHandlers.handleAudio],
  ["play", GenerationHandlers.handlePlay],
  ["stop", GenerationHandlers.handleStop],

  // ─── 算子命令 ───
  ["add", OperatorHandlers.handleAdd],
  ["sub", OperatorHandlers.handleSub],
  ["mul", OperatorHandlers.handleMul],
  ["div", OperatorHandlers.handleDiv],
  ["mod", OperatorHandlers.handleMod],
  ["pow", OperatorHandlers.handlePow],
  ["max", OperatorHandlers.handleMax],
  ["min", OperatorHandlers.handleMin],
  ["rand", OperatorHandlers.handleRand],
  ["sin", OperatorHandlers.handleSin],
  ["cos", OperatorHandlers.handleCos],
  ["log", OperatorHandlers.handleLog],
  ["abs", OperatorHandlers.handleAbs],
  ["sqrt", OperatorHandlers.handleSqrt],
  ["round", OperatorHandlers.handleRound],
  ["len", OperatorHandlers.handleLen],
  ["length", OperatorHandlers.handleLen],
  ["trim", OperatorHandlers.handleTrim],
  ["split", OperatorHandlers.handleSplit],
  ["join", OperatorHandlers.handleJoin],
  ["replace", OperatorHandlers.handleReplace],
  ["re", OperatorHandlers.handleReplace],
  ["match", OperatorHandlers.handleMatch],

  // ─── JS-Slash-Runner 兼容命令 ───
  ["event-emit", JSSlashRunnerHandlers.handleEventEmit],
  ["eventemit", JSSlashRunnerHandlers.handleEventEmit],
  ["audioenable", JSSlashRunnerHandlers.handleAudioEnable],
  ["audioplay", JSSlashRunnerHandlers.handleAudioPlay],
  ["audioplaypause", JSSlashRunnerHandlers.handleAudioPlayPause],
  ["audioimport", JSSlashRunnerHandlers.handleAudioImport],
  ["audioselect", JSSlashRunnerHandlers.handleAudioSelect],
  ["audiomode", JSSlashRunnerHandlers.handleAudioMode],
  ["audiopause", JSSlashRunnerHandlers.handleAudioPause],
  ["audioresume", JSSlashRunnerHandlers.handleAudioResume],
  ["audiostop", JSSlashRunnerHandlers.handleAudioStop],
  ["audiovolume", JSSlashRunnerHandlers.handleAudioVolume],
  ["audioqueue", JSSlashRunnerHandlers.handleAudioQueue],
  ["audioclear", JSSlashRunnerHandlers.handleAudioClear],
]);

/* ═══════════════════════════════════════════════════════════════════════════
   注册表操作 - 好品味：简洁直接的API
   ═══════════════════════════════════════════════════════════════════════════ */

/** 获取命令处理器 */
export function getCommandHandler(name: string): CommandHandler | undefined {
  return COMMAND_REGISTRY.get(name.toLowerCase());
}

/** 注册新命令 */
export function registerCommand(name: string, handler: CommandHandler): void {
  COMMAND_REGISTRY.set(name.toLowerCase(), handler);
}

/** 检查命令是否存在 */
export function hasCommand(name: string): boolean {
  return COMMAND_REGISTRY.has(name.toLowerCase());
}

/** 获取所有已注册命令名 */
export function getRegisteredCommands(): string[] {
  return Array.from(COMMAND_REGISTRY.keys());
}
